print('Enter two no')
p=int(input())
g=int(input())
print('Less than',p<g)
print('Greater than',p>g)
print('Less than equal to',p<=g)
print('Greater than equal to',p>=g)
print('Equal to Equal to',p==g)
print('Not equal to',p!=g)
